lib/config-ui.js
lib/shaped-script.js

Script can now set defaults for max dex for medium armor and half-proficiency saves houserules
fixes: #14

feat(config): Support max dex for medium armor and half-proficiency saves houserules

---

lib/config-ui.js
lib/shaped-script.js

feat(config): Add auto HD and Roll HD on drop options to config UI

---

lib/sanitise.js

fix(statblock-import): Escape &lt; etc

---

lib/entity-lookup.js
lib/entry-point.js

fix(json-import): Make it more tolerant of patch versions of JSON files

---

lib/command-parser.js
lib/config-ui.js
lib/entry-point.js
lib/shaped-script.js
lib/user-error.js
test/test-command-parser.js

Includes options for ritual casting and re-casting at a different level where possible. closes: #16

feat(spell-slots): Automatically decrement spell slots on casting

---

lib/shaped-script.js

fix(spell-slots): Disable spell slot handling, not ready for use yet.

---

lib/rest-manager.js
lib/shaped-script.js

- Added chat output as the character who performed the rest
- Support for the rest buttons Kryx added to the sheet
- Made looking for the "recharge" value on the sheet more flexible
- Now remove 1 level of exhaustion on long rest

Rest output

---

lib/migrations.js
lib/shaped-script.js
test/test-migrations.js

fix(config): Fix upgrade crash

---

lib/config-ui.js
lib/migrations.js
lib/rest-manager.js
lib/shaped-script.js

Add houserule for long rests granting full HD, but no HP

feat(rests): Add new long rest house rule

---

lib/config-ui.js
lib/migrations.js
lib/shaped-script.js
lib/trait-manager.js
test/test-migrations.js

If enabled in config (on by default) trait uses will be automatically decremented when clicked.

feat(traits): Add auto consume traits

---

lib/entry-point.js
lib/srd-converter.js

fix(spell-import): Fix duplicate spell description text on import

---

README.md
lib/command-parser.js
lib/entity-lookup.js
lib/entry-point.js
lib/shaped-script.js
test/test-entity-lookup.js

Fixes #9
See README.md for more details on usage

feat(spell-import): Allow spell import option to import spells according to criteria

---

lib/migrations.js
lib/shaped-script.js
test/test-shaped-script.js

fixes #15
Configure vision for tokens for imported monsters based on value of senses attribute

feat(tokens): Auto-configure vision based on senses

---

lib/config-ui.js
lib/migrations.js
lib/shaped-script.js

feat(config): Add option for default char sheet page

---

lib/config-ui.js
lib/shaped-script.js

- Reorged some menus and split other menus to make all configs fit within a max 595px height in order to support smaller displays
- Added Aura visibility options
fixes: #24
fixes: #100

fix(config): Make config UI fit on small displays

---

lib/advantage-tracker.js

Ignore npcs

---

lib/ability-maker.js
lib/command-parser.js
lib/shaped-config.js
lib/shaped-module.js
lib/shaped-script.js
test/test-command-parser.js
test/test-shaped-script.js

fixes #116
Also includes the beginnings of a modularisation refactor - move all command functions out into their
own modules.

feat(abilities): Allow creation of abilities for individual traits

---

lib/ability-maker.js
test/test-shaped-script.js

feat(abilities): Add rest options for ability creation

---

lib/shaped-script.js

feat(import): Update token bars for original token on import

---

lib/ability-maker.js

feat(abilities): Add "spells" option for token actions

---

lib/shaped-script.js

fix(hp-rolling): Fix HP rolling on drop bug introduced in last release

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js

feat(abilities): Add default token action option for spells

---

lib/advantage-tracker.js
lib/migrations.js
lib/shaped-config.js
lib/shaped-script.js

BREAKING CHANGE: This resets most of the default new character settings - you will need to put them back to your desired values using !shaped-config

fix(config): Update configuration options to match changes for sheet 4.2.1

---

lib/srd-converter.js

feat(spell-import): Support adding casting stat to secondary damage (for Green Flame Blade)

---

lib/rest-manager.js

fix(rest-handling): Fix errors on rest when HP and HD values not set

---

README.md
lib/config-ui.js

closes #161
(Note that the fix for ammo was actually done in the roll20-wrapper project - the release will automatically pick that up from npm)

fix(ammo-processing): Fix bug introduced in ammo handling in 3.1.0

---

lib/srd-converter.js

BREAKING CHANGE: Will not work correctly with character sheet < 5.0.2

feat(spell-import): Support translations for various spell fields

---

lib/shaped-script.js

fix(shaped-support): Get player HD working again with new translated output

---

lib/srd-converter.js

fix(spell-import): Fix bug with spells with material cost

---

lib/migrations.js

fix(advantage-tracker): Make advantage tracker silent for new installs

---

lib/migrations.js
lib/shaped-config.js
lib/shaped-script.js
test/test-shaped-script.js

fix(config): Don't create attributes for sheet options with default values

---

lib/migrations.js
lib/shaped-config.js
lib/shaped-script.js

feat(config): Apply character defaults to manually created characters.

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js
lib/shaped-script.js
test/test-migrations.js

feat(config): Implement configuration for custom Saving throws

---

lib/ability-maker.js
lib/advantage-tracker.js
lib/command-parser.js
lib/config-ui.js
lib/reporter.js
lib/rest-manager.js
lib/shaped-module.js
lib/shaped-script.js
lib/trait-manager.js
test/dummy-reporter.js
test/test-command-parser.js

feat(command-proc): Implement security check + send messages to correct players

---

lib/json-validator.js

fix(json-import): Fix broken version validation

---

lib/ability-maker.js
lib/config-ui.js
lib/shaped-script.js

fix(ability-maker): Adjust ordering of default token actions

---

lib/ability-maker.js
lib/shaped-config.js

feat(ability-maker): Add short option for advantage token actions

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js

feat(config): Add expertise_as_advantage option for new characters

---

resources/mmFormatSpec.json

feat(parsing): Add a couple of custom skills for Kryx

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js

feat(config): Add hide options for new characters

---

lib/shaped-config.js
lib/shaped-script.js

feat(config): Add hidden option for specifying custom skills data

---

README.md

docs: Update docs to correspond to latest changes

---

lib/config-ui.js

fix(config): fix broken text size UI

---

lib/shaped-script.js
test/test-shaped-script.js

fix(token-config): Round fractional numbers on darkvision

---

lib/srd-converter.js

fix(spell-import): Set toggle_details to 0 after importing spells

---

lib/shaped-config.js

fix(config): Fix spell text size option for new characters

---

lib/shaped-script.js

feat(token-vision): Automatically set vision for PCs from senses

---

lib/shaped-script.js

fix(apply-defaults): Ensure apply-defaults saves the default token

---

lib/shaped-script.js

fix(token-numbering): NUMBERED shouldn't be applied to PC tokens

---

lib/reporter.js

fix(chat-output): Fix bug with multiple players with same forename

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js

feat(config): Add Hit Dice Output and Show Rests to "!shaped-config"

---

lib/entity-lookup-result-reporter.js
lib/entity-lookup.js
lib/entry-point.js
package.json
test/test-entity-lookup.js
test/test-json-validator.js

closes #248
JSON databases can now be named and have explicit dependencies on each other
so out-of-order loading of multiple dependent files is possible. Also allows for
more useful error reporting.

feat(json-import): Internal improvements to JSON database loading

---

lib/rest-manager.js

feat(rests): Regain spell points and warlock slots on rests

---

lib/monster-post-processor.js
resources/mmFormatSpec.json
test/data/ancientWhiteDragon.json
test/data/ancientWhiteDragon.txt
test/data/mindFlayer.json
test/data/mindFlayer.txt

fix(parser): Traits should allow for parenthesis.

---

lib/ability-maker.js

fix(token-actions): Fix broken token action creation for individual spells

---

lib/trait-manager.js

feat(traits): Decrement traits by per_use value if present

---

lib/srd-converter.js

feat(spell-import): Fix higher level text to be in its own field

---

lib/shaped-script.js

feat(monster-import): --as option for monsters

---

lib/monster-post-processor.js
test/data/deathKnight.json
test/data/mindFlayer.json
test/data/talisTheWhite.json
test/test-monster-post-processor.js

fix(monster-import): Don't strip bracketed info from spell names

---

lib/trait-manager.js

fix(traits): Don't warn when no uses value present

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js

feat(config): Update initiative settings for 9.1.0

---

lib/ability-maker.js

feat(token-actions): Make abilities use ids to survive name changes

---

lib/importer.js
lib/reporter.js
test/test-importer.js

Also made script output use roll template for shinier UI

fix(import): Import wasn't whispering to GM/player

---

lib/shaped-script.js

feat(spell-slots): Auto-decrement spell slots

---

lib/ability-maker.js
lib/config-ui.js
lib/importer.js
lib/migrations.js
lib/shaped-config.js

closes #272
Also added missing sections to list of available token actions

feat(token-actions): Add option for showing recharge on token actions

---

lib/config-ui.js
lib/migrations.js
lib/shaped-config.js

feat(config): Add all latest 9.x options to !shaped-config

---

README.md
lib/importer.js

feat(import): Add command that imports based on token names

---

lib/rest-manager.js
lib/shaped-script.js
lib/uses-manager.js

feat(uses): Decrement legendary points + restore on turn recharge

---

lib/importer.js
lib/shaped-script.js
lib/uses-manager.js
test/dummy-roll20-object.js
test/test-importer.js

fix(import): Workaround roll20 bug with max values under API sheetworkers

---

lib/importer.js

fix(update-character): Fix bug on update character

---

lib/srd-converter.js

fix(import): Make lair actions import properly again

---

README.md
lib/config-ui.js
lib/importer.js
lib/migrations.js
lib/shaped-config.js

feat(import): Add option to use same label for all tokens

---

lib/shaped-script.js

fix(slots): Don't decrement for repeat casts (requires 9.2.2)

---

lib/command-parser.js
lib/importer.js
lib/shaped-script.js
test/test-ability-maker.js
test/test-shaped-script.js

Introduced version checking as well to prevent problems with mismatched
character sheet versions. Partial fix for #12.
closes #334

fix(spell-import): Importing Spell List gives an error

---

lib/entry-point.js
lib/migrations.js
lib/modules/config-ui.js
lib/modules/spell-manager.js
lib/shaped-config.js
test/test-spell-manager.js

feat(spells): Make automatic spell slot processing a per-character setting

---

lib/migrations.js
lib/modules/config-ui.js
lib/modules/rest-manager.js
lib/shaped-config.js
test/test-rest-manager.js

fix(rests): Make long rest HP behaviour more configurable

---

lib/entry-point.js

fix(startup): Scale timeout to size of campaign

---

lib/modules/hd-manager.js
lib/modules/rest-manager.js

fix(rests-and-hd): Pay attention to reduced HP max

---

lib/modules/importer.js

fix(import): Ensure saves/skills always include PB

---

lib/command-parser.js
lib/entry-point.js
lib/shaped-config.js

fix(config): All commands warn when config is not upgraded

---

lib/chat-watcher.js
lib/modules/ammo-manager.js
lib/modules/death-save-manager.js
lib/modules/fx-manager.js
lib/modules/hd-manager.js
lib/modules/spell-manager.js
lib/modules/uses-manager.js
lib/shaped-module.js
test/test-ammo-manager.js

feat(output): Whisper results if original command/trigger was whispered

---

lib/modules/rest-manager.js
test/test-rest-manager.js

feat(rests): Implement recharge 5-6 style recharges

---

lib/entry-point.js
lib/modules/config-ui.js
lib/modules/importer.js
lib/reporter.js
test/test-importer.js

fix(import): Default token bars not applied to 1st token

---

gulpfile.js
lib/event-dispatcher.js
lib/modules/ammo-manager.js
lib/modules/config-ui.js
lib/modules/rest-manager.js
lib/reporter.js
lib/shaped-config.js
lib/shaped-module.js
test/test-ammo-manager.js

feat(ammo): Prompt for ammo recovery at end of combat

---

lib/modules/config-ui.js
lib/shaped-config.js

feat(config): Add settings for Automatically roll damage

---

lib/entry-point.js
lib/modules/death-save-manager.js

fix(death-saves): Don't moan about negative HP

---

lib/modules/config-ui.js
lib/modules/monster-manager.js
lib/shaped-config.js

feat(token-defaults): Provide option to only link bars for PCs

---

lib/modules/monster-manager.js
test/dummy-reporter.js

fix(import): Stop Errors being swallowed for monster import

---

lib/modules/monster-manager.js

feat(monster-list): Click to remove existing

---

lib/entry-point.js

fix(startup): Fix version not found bug on startup

---

lib/modules/rest-manager.js
lib/modules/sheetworker-chat-output.js

fix(rests): Stop crash on turn change

---

lib/modules/spell-manager.js

fix(spell-slots): Make Divine Smite deduct spell slots.

---

lib/entity-lookup.js

fix(spell-list): Fix problem with patching archetypes

---

lib/modules/uses-manager.js

closes #461
BREAKING CHANGE: This script no longer works with sheets
below version 11.4.0

fix(uses): Fix legendary action uses decrementing

---

lib/entry-point.js

fix(startup): Make "Upgrade the sheet" less confusing

---

lib/modules/monster-manager.js

fix(import): Don't show monster List after import

---

.travis.yml
lib/modules/config-ui.js

fix(config-ui): Fix error on custom saves back button
